language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/notes
deploy:
  provider: heroku
  app: alchemy-notes
  api_key:
    secure: S4gTCdpEWt56hDVmXz7ojhNSwtRoa+TQCTmhBiaq5YENGpcZf7LeJYzb3mCZj3mMm5mTSt5CLxhfQ62cImXfsWfdB24CpWvVDzMk3v7u8l0ou9qIxVQJSoYEQGFOpMkPW9VplDUOUXUCUk+Upt5Y+5w06hKBPMpudwYG4z5I1bezcSijV9AMtz2P9OEKEYFmw+Nxfileck6/y16h+GoQs6NYTrf+QGG6FtwEGvteH0sfPJAukJoBhXqeeSm1JLD/PP/4+fWh/Cl08Mwas1NlxqiW7JVUH4XWeCAjYe/FpolaxP6cKugTrs9MyegPKay1fCQZvm+5S7OBBSgaLQm+l4UoYcOlWMXwfdE8yKYIe5pp9JwBsVJeHVfcFM2KK+KTuWlX0MIytx0vMHYzkHrVEr26h4+IlqolVb4sZqxReAu8qTPgNQrXTAEv7ot4Vzljejh3u0xxTAzqf8kdXsSApiIMIQHW5UudB3JR4cOAakM3TaMl4Pt+2KRbiYLO8F3TrY5dkKai/B9kXkqXIxiB/Bt3ZW/IcvPFEFViHuRuVrAkt5y4hqFVH7shWGVEtfqrsqko0wLu8lhyRZ79kCAJ/snr2uYFV+P0VzEHCYDKIYYGJ+HBUy1gBeJYsSF0sQNYdhbm4z4aj+6X55loURshCYOBTj4pOTnuVMfegC5KVXo=
