language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/notes
deploy:
  provider: heroku
  app: alchemy-notes
  api_key:
    secure: K9MavuYprcnkbHLKE186w9rcyegppbhkEAPa1+fzof6kkBAfbjht6p/vIHI4S7DSGKTeSSifG79Xl5fIbX5uWBbfvoudUoSgBfYNtnqYVKS1UgEy+XAMBQWC6zgTW46CUzTbXOTEarinzSDVR8GG8irixZDTV38rvkdz+l1waJyeLxInv3o8lMNtTt9GSp1ve+61IHBVB+LPgZ7OiBuGfug1jW6whWFlrf4qzLPEKRMGLXy2QO81Qd0Y6EzoZTz2SFsSDmJ+FSdxxC/ByksAWacULuJJ48560FlCwLgwPYaZrMBg3IJJseP0XTDGKx7fj1poyMuDRhRbkIII+4v+YNPfGlKRbFQQ7pGvkSBmr/4Spqm9diWhieRQb7GuWVyoPi+hUFRCAp5FHzNbp1t/FT8j5+423Jl/k98fPuP5HJRS72b3Akit2b+hWnxG9sEL87mmBdvSGqHxsXb8GGwqZw0zREP0Cbyu7uYoraaOROATKUvEK+xicUW5P1vBQjj1VGxrUXy38ubDuiwiasXIZ5b6SW5icJ/BXfcKf24tby5PLKiT4jxe6ayXc7EOPw5SEBbdAJ8slcUOnjNxJ4jdxsZEiJk81tzg977Ut1OY39xk/nSrbsLp3NwmJL0y7BvRxyatQP6LYjSLFCF+bV/CP5Q/SZh0QZAF7WfjguJWaoI=
